### PR TITLE
Disable Process#clock_gettime mocking by default

### PR DESCRIPTION
**Pull request by alexcwatt**
https://github.com/travisjeffery/timecop/issues/425

### CODE REVIEW

**Comment by alexcwatt** [comment]
@joshuacronemeyer This might be the simplest fix. I was also thinking it could be nice if the `TimeStackItem` new about whether or not we are mocking `Process#clock_gettime` so it could be an argument to `Timecop.freeze` and `Timecop.travel` in the future.

Just wanted to get something up quickly for feedback.

**Comment by joshuacronemeyer** [comment]
@alexcwatt code looks good. I think it's worth a mention in the README. Let me know if you'd like me to write something and add to this PR or if you got it. And thanks for the quick turnaround! 

@olly and @nerdrew from the next release the process clock freezing will be opt-in. Feel free to weigh in on this.

**Comment by olly** [comment]
@joshuacronemeyer I'm happy with that proposal. I don't personally have any need to mock the `Process` clock, but to me it seems like needing to is a pretty niche use-case and so opting-in is appropriate.

**Comment by alexcwatt** [comment]
Glad it looks good! Feel free to take over the PR to update README. Thank you for flagging this issue; I definitely didn't anticipate it.

**Comment by joshuacronemeyer** [comment]
ok. i will shepherd this to a release this weekend. thanks all. @alexcwatt i actually wasn't surprised that something like this cropped up, even minor changes tend to bring folks out of the woodwork pretty fast.

**Comment by joshuacronemeyer** [comment]
closed this in favor of this https://github.com/travisjeffery/timecop/pull/427 because I don't know what i'm doing haha. 

All i could figure out how to do was create my own branch and merge alex's branch into it and then make a PR from that.

**Pull request closed without merging**
