### PR TITLE
Fix arity of Date.parse and DateTime.parse

### PR DESCRIPTION
**Pull request by cgunther**
485c4a4 introduced a regression where the method signature of `Date.parse` and `DateTime.parse` no longer matched the stdlib version. Both support 3 arguments, however the patched method only accepted one. This updates them to accept any number of arguments, passing them as is to the original method when the patch doesn't apply (not a weekday), or grabbing just the first argument when the patch does apply.

This also included a commit to rename a test file to have the _test suffix so it'd be picked up by the test runner.

### CODE REVIEW

**Comment by ThomasKoppensteiner** [comment]
+1

**Comment by cedrics** [comment]
:+1:

**Comment by baburdick** [comment]
+1

**Comment by travisjeffery** [comment]
Awesome! Thanks!

**Comment by cgunther** [comment]
Sweet, thanks for the quick merge/release!

**Comment by ThomasKoppensteiner** [comment]
@cgunther thank you for fixing my fix. I forgot to check my implementation against the stdlib. I have learned my lesson. ;)

**Comment by cgunther** [comment]
You're welcome!

**Pull request merged**
