### PR TITLE
Add an explicit warning for sql and javascript

### PR DESCRIPTION
**Pull request by cyrilchampier**
related to https://github.com/travisjeffery/timecop/issues/235

### CODE REVIEW

**Comment by dmitry** [comment]
@cyrilchampier looks good to me, wording is not perfect but at least other ones could find this helpful when they step at the same thing.

**Comment by cyrilchampier** [comment]
@dmitry do you need me to do something before you merge?

**Comment by dmitry** [comment]
@cyrilchampier I'm not the maintainer. We have to ask @travisjeffery for that.

**Comment by cyrilchampier** [comment]
This seems staled, I close it.

**Pull request closed without merging**
