### PR TITLE
Add dependabot configuration file

### PR DESCRIPTION
**Pull request by jwillemsen**
With this configuration file dependanbot will create PRs when a github or ruby gem dependency is out of date (see https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates)

### CODE REVIEW

**Comment by jwillemsen** [comment]
Keeps the github actions as proposed by #276 up to date

**Comment by jwillemsen** [comment]
In the github projects settings under "Security & Analysis" dependabot should be enabled, would recommend to enable all security analysis features there

**Comment by joshuacronemeyer** [comment]
Thanks so much @jwillemsen for all the great dev quality of life PRs you've made recently. The actions builds are so much faster than travis. I love it!

**Comment by jwillemsen** [comment]
No problem, github actions make life much easier. a lot is possible, for example on a publish of a new release on github you can automatically create and publish to rubygems, see for example https://github.com/RemedyIT/ridl/blob/master/.github/workflows/gem_release.yml where we do that

**Pull request merged**
