### PR TITLE
Add Ruby 3.1 to CI

### PR DESCRIPTION
**Pull request by petergoldstein**
As Ruby 3.1 is released, it should be added to CI as a formal entry.

### CODE REVIEW

**Comment by joshuacronemeyer** [comment]
thanks @petergoldstein. Merging this and merged a couple other PRs along with it to hopefully get back to a green build. Looks like the failures were from ruby >=3.1 removing some stuff from the standard lib that older nokogiris required. Updating nokogiri solved those failures.

**Comment by petergoldstein** [comment]
@joshuacronemeyer Great.  I actually was planning on getting this running myself, but I'm glad you got it done.

**Comment by joshuacronemeyer** [comment]
I couldn't get our build passing for ruby 2.5. If you feel like it you could take a look at those build failures. Since ruby 2.5 support ended in 3/2021 I went ahead and removed it in favor of getting a passing build.

**Comment by petergoldstein** [comment]
I think removing Ruby 2.5 is the right move.  It's EOL and Ruby 2.6 is EOLing in ~2 months.

**Pull request merged**
